### ISSUE TITLE
Проверка комплиятора

### ISSUE THREAD

**Issue by continue98** [Daniel-Cortez/samp-plugin-template#2]
Привет. Наверное, стоит добавить проверку под UNIX, чтобы проверяло битность компилятора?
Аля:

`if(CMAKE_COMPILER_IS_GNUCXX)
	if(NOT CMAKE_SIZEOF_VOID_P EQUAL 4)
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -m32")
	endif()
endif()`

Ибо, под x64 битным дистром, будет собирать 64 битный код для плагина.

**Comment by Daniel-Cortez** [comment]
Fixed in #3.
